global:
  environment: dev

reservation:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

member:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

ingress:
  hosts:
    - host: dev.api.nekocafe.local

observability:
  tracing:
    samplingRate: 1.0   # 开发环境全量采样
  logging:
    level: DEBUG
