# Staging environment overrides
global:
  environment: staging

reservation:
  replicaCount: 2

member:
  replicaCount: 2

canary:
  enabled: true
  weight: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
