# Dev environment overrides
global:
  environment: dev

reservation:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

member:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

autoscaling:
  enabled: false

observability:
  prometheus:
    enabled: false
  grafana:
    enabled: false
