global:
  environment: staging

reservation:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 512Mi

member:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 512Mi

canary:
  enabled: true
  weight: 5

ingress:
  hosts:
    - host: staging.api.nekocafe.local

observability:
  tracing:
    samplingRate: 0.5
  logging:
    level: INFO
